# Generated by Django 5.2.4 on 2025-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
